kind = "web"
previewPath = "/"
title = "Fernando López"
version = "1.0.0"
id = "artifacts/fernando-lopez"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20273

[services.development]
run = "pnpm --filter @workspace/fernando-lopez run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fernando-lopez", "run", "build" ]
publicDir = "artifacts/fernando-lopez/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20273"
BASE_PATH = "/"
